version: 0.1
environment_variables:
  plaintext:
    JAVA_HOME: "/usr/lib/jvm/java-7-openjdk-amd64"
phases:
  install:
    commands:
      - echo Nothing to do in the install phase
  pre_build:
    commands:
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/EmployeeApplication.war
  discard-paths: yes